steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - vite
  - --entry-point=vite
  - --region=us-central1
  - --trigger-http
  - --runtime=nodejs16
  - --allow-unauthenticated
artifacts:
  objects:
    location: 'gs://[STORAGE_LOCATION]/'
    paths: ['dist']