steps:
  - name: node:lts
    entrypoint: npm
    args: ['install']
  - name: node:lts
    entrypoint: npm
    args: ["run", "create-env"]
    env:
    - 'VITE_CONTENTFUL_SPACE_ID=${_VITE_CONTENTFUL_SPACE_ID}'
    - 'VITE_CONTENTFUL_ACCESS_TOKEN=${_VITE_CONTENTFUL_ACCESS_TOKEN}'
  - name: node:lts
    entrypoint: npm
    args: ['run', 'build']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: vite-studio
  _DEPLOY_REGION: us-central1