steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - vite
  - --source=./dist/server/
  - --region=us-central1
  - --runtime=nodejs16
  - --trigger-http
  - --allow-unauthenticated
  