steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'node'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'node'
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - vite
  - --source=.
  - --region=us-central1
  - --runtime=nodejs16
  - --trigger-http
  - --allow-unauthenticated
  